# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Keyway < Formula
  desc "GitHub-native secrets management CLI"
  homepage "https://keyway.sh"
  version "0.4.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/keywaysh/cli/releases/download/v0.4.1/keyway_0.4.1_darwin_amd64.tar.gz"
      sha256 "c35111ddc55dbd6e51fa27aef085019b5c80e83b1672d9e403a36c04dedb8878"

      def install
        bin.install "keyway"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/keywaysh/cli/releases/download/v0.4.1/keyway_0.4.1_darwin_arm64.tar.gz"
      sha256 "3aac14b933ef90b267a9400fbe352adf3d8bceb1bd60f897880ef4806003b643"

      def install
        bin.install "keyway"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/keywaysh/cli/releases/download/v0.4.1/keyway_0.4.1_linux_amd64.tar.gz"
      sha256 "2259995a75887b06969e4df715ec56c23c6dba7038b017cc46cfa7373cfc14aa"
      def install
        bin.install "keyway"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/keywaysh/cli/releases/download/v0.4.1/keyway_0.4.1_linux_arm64.tar.gz"
      sha256 "f6bdb43afae7e58ed6f13f71ec0a23a4271b37655719eadcdd0976654dcfccf9"
      def install
        bin.install "keyway"
      end
    end
  end

  test do
    system "#{bin}/keyway", "--version"
  end
end
