# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Keyway < Formula
  desc "GitHub-native secrets management CLI"
  homepage "https://keyway.sh"
  version "0.3.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/keywaysh/cli-go/releases/download/v0.3.3/keyway_0.3.3_darwin_amd64.tar.gz"
      sha256 "70261448f93e197fdb685a5d6f90fa3c2cf8a92fe519f64800ac05d74f9d7c58"

      def install
        bin.install "keyway"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/keywaysh/cli-go/releases/download/v0.3.3/keyway_0.3.3_darwin_arm64.tar.gz"
      sha256 "bb9f1ec41b8733b64bed8ca36d12751f2ac1fd4196dd601193fa407a0d927a49"

      def install
        bin.install "keyway"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/keywaysh/cli-go/releases/download/v0.3.3/keyway_0.3.3_linux_amd64.tar.gz"
      sha256 "b7e7c60c85b1aa0fd74b58b0ff2e50ef7f04f35f89ee0475248dd1eca887c617"
      def install
        bin.install "keyway"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/keywaysh/cli-go/releases/download/v0.3.3/keyway_0.3.3_linux_arm64.tar.gz"
      sha256 "10dbe0169426488a97039be87cb742984ec01da909e7255c50dd2bfdade39672"
      def install
        bin.install "keyway"
      end
    end
  end

  test do
    system "#{bin}/keyway", "--version"
  end
end
