# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Keyway < Formula
  desc "GitHub-native secrets management CLI"
  homepage "https://keyway.sh"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/keywaysh/cli/releases/download/v0.5.0/keyway_0.5.0_darwin_amd64.tar.gz"
      sha256 "cb99a2b5459690e1dc9a89082e60f55c14f29b1397096d3598a9906ce4227195"

      def install
        bin.install "keyway"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/keywaysh/cli/releases/download/v0.5.0/keyway_0.5.0_darwin_arm64.tar.gz"
      sha256 "0717e21927eab050009a330570ee3f8d47954a0df23e43a61f1b75d3f4af9544"

      def install
        bin.install "keyway"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/keywaysh/cli/releases/download/v0.5.0/keyway_0.5.0_linux_amd64.tar.gz"
      sha256 "a94f044506450de312cbb1680f6bd17f18bc8b870955548179824d16da9d5d3e"
      def install
        bin.install "keyway"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/keywaysh/cli/releases/download/v0.5.0/keyway_0.5.0_linux_arm64.tar.gz"
      sha256 "de2713e71482bcbea65ebf17fa2d2afcc3fecf8a98aa1a72b8272dc71b3bd4a1"
      def install
        bin.install "keyway"
      end
    end
  end

  test do
    system "#{bin}/keyway", "--version"
  end
end
